using Microsoft.EntityFrameworkCore.Migrations;

namespace GuIA.Infrastructure.Migrations;

/// <summary>
/// Marker migration for the initial database schema.
/// Run 'dotnet ef migrations add CreateInitialSchema' to generate the actual migration.
/// </summary>
public partial class CreateInitialSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Schema will be generated by running:
        // dotnet ef migrations add CreateInitialSchema --output-dir Migrations
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
